# Generated by Django 4.1 on 2025-02-18 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="미정",
                        max_length=255,
                        unique=True,
                        verbose_name="기업명",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        default="기타", max_length=255, verbose_name="종목"
                    ),
                ),
                (
                    "main_product",
                    models.CharField(
                        default="정보 없음", max_length=255, verbose_name="주요제품"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("구매처", "구매처"), ("판매처", "판매처")],
                        max_length=50,
                        verbose_name="거래처 구분",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="networkapp.company",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partners",
                        to="networkapp.company",
                    ),
                ),
            ],
        ),
    ]
